version = "3.10.7"
runner.dialect = scala3

maxColumn = 120

indent.main = 4
indent.callSite = 4
indent.commaSiteRelativeToExtends = 4

align {
  preset = some
  tokens = ["<-"]
}

rewrite.rules = [SortModifiers]
